Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using skiShop.Models;
using Microsoft.AspNetCore.Authorization;
using System.Text;
using skiShop.Services;
using System.Xml.Serialization;
using System.IO;
using System.Xml;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;

namespace skiShop.Controllers
{
    public class RentalsController : Controller
    {
        private ILogger _logger;
        private readonly skiShopContext _context;
        private RentalService _rentalService;

        public RentalsController(ILogger<RentalsController> logger, skiShopContext context, RentalService rentalService)
        {
            _logger = logger;
            _context = context;
            _rentalService = rentalService;
            link = new List<Rental>();
        }

        // GET: Rentals
        [Authorize]
        public async Task<IActionResult> Index(int Filter, string SearchString, int? page, string currentFilter, int TypeFilter)
        {
            //ViewData["CurrentSort"] = sortOrder;
            if (SearchString != null)
            {
                page = 1;
                CookieOptions cookieOptions = new CookieOptions();
                Response.Cookies.Append("Search", $"{Filter}_{SearchString}_{page}_{SearchString}_{TypeFilter}");
            }
            else
            {
                SearchString = currentFilter;
            }
            ViewData["CurrentFilter"] = SearchString;


            var Rentals = from m in _context.Rental select m;

            if (!string.IsNullOrEmpty(SearchString))
            {
                try
                {
                    if (Filter == 0)
                    {
                        if (!SearchString.Contains(' ')) { Filter = 1; }
                        #region Full Name Logic
                        else
                        {
                            var name = SearchString.Split(' ');
                            var fName = Rentals.Where(r => r.FirstName.Contains(name[0]));
                            var lName = Rentals.Where(r => r.LastName.Contains(name[1]));
                            Rentals = fName.Intersect(lName);
                            var exampl1 = lName.Except(fName);
                            var exampl2 = fName.Except(lName);
                            Rentals = Rentals.Union(exampl1).Union(exampl2);
                            if (TypeFilter == 1)
                            {
                                Rentals = Rentals.Where(m => m.DailyRental == false);
                            }
                            if (TypeFilter == 2)
                            {
                                Rentals = Rentals.Where(m => m.DailyRental == true);
                            }
                        }
                        #endregion
                    }
                    if (Filter == 1)
                    {
                        #region First Name Logic
                        var fNameMatches = Rentals.Where(r => r.FirstName.Contains(SearchString));
                        var lNameMatches = Rentals.Where(r => r.LastName.Contains(SearchString));
                        if (TypeFilter == 0)
                        {
                            Rentals = fNameMatches.Union(lNameMatches);
                        }
                        if (TypeFilter == 1)
                        {
                            Rentals = fNameMatches.Union(lNameMatches).Where(r => r.DailyRental == false);
                        }
                        if (TypeFilter == 2)
                        {
                            Rentals = fNameMatches.Union(lNameMatches).Where(r => r.DailyRental == true);
                        }
                        #endregion
                    }
                    if (Filter == 2)
                    {
                        #region Last Name Logic
                        var fNameMatches = Rentals.Where(r => r.FirstName.Contains(SearchString));
                        var lNameMatches = Rentals.Where(r => r.LastName.Contains(SearchString));
                        if (TypeFilter == 0)
                        {
                            Rentals = lNameMatches.Union(fNameMatches);
                        }
                        if (TypeFilter == 1)
                        {
                            Rentals = lNameMatches.Union(fNameMatches).Where(r => r.DailyRental == false);
                        }
                        if (TypeFilter == 2)
                        {
                            Rentals = lNameMatches.Union(fNameMatches).Where(r => r.DailyRental == true);
                        }
                        #endregion
                    }
                    if (Filter == 3)
                    {
                        #region Email Logic
                        if (TypeFilter == 0)
                        {
                            Rentals = Rentals.Where(r => r.EmailAddress.Contains(SearchString));
                        }
                        if (TypeFilter == 1)
                        {
                            Rentals = Rentals.Where(r => r.EmailAddress.Contains(SearchString)).Where(r => r.DailyRental == false);
                        }
                        if (TypeFilter == 2)
                        {
                            Rentals = Rentals.Where(r => r.EmailAddress.Contains(SearchString)).Where(r => r.DailyRental == true);
                        }
                        #endregion
                    }
                    if (Filter == 4)
                    {
                        #region Phone Number Logic
                        var PhoneNumber1 = Rentals.Where(r => r.PhoneNumber.ToString().Contains(SearchString));
                        var PhoneNumber2 = Rentals.Where(r => r.PhoneNumber2.ToString().Contains(SearchString));
                        foreach (var num in PhoneNumber2)
                        {
                            PhoneNumber1.Append(num);
                        }
                        if (TypeFilter == 0)
                        {
                            Rentals = PhoneNumber1;
                        }
                        if (TypeFilter == 1)
                        {
                            Rentals = PhoneNumber1.Where(r => r.DailyRental == false);
                        }
                        if (TypeFilter == 2)
                        {
                            Rentals = PhoneNumber1.Where(r => r.DailyRental == true);
                        }
                        #endregion
                    }
                    if (Filter == 5)
                    {
                        #region ?????
                        var name = SearchString.Split(' ');
                        var fName = Rentals.Where(r => r.FirstName.Contains(name[0]));
                        var lName = Rentals.Where(r => r.LastName.Contains(name[1]));
                        if (SearchString.Contains(' '))
                        {
                            Rentals = fName.Intersect(lName).Where(r => r.DailyRental == true);
                        }
                        else
                        {
                            Rentals = Rentals.Where(x => x.FirstName.Contains(SearchString) || x.LastName.Contains(SearchString)).Where(r => r.DailyRental == true);
                        }
                        #endregion
                    }
                }
                catch (Exception e) { _logger.LogError($"Error Within Search Algorithm - Exception: {e.Message}"); }
            }
            else
            {
                try
                {
                    if (TypeFilter == 1)
                    {
                        Rentals = Rentals.Where(r => r.DailyRental == false);
                    }
                    if (TypeFilter == 2)
                    {
                        Rentals = Rentals.Where(r => r.DailyRental == true);
                    }
                }
                catch (Exception e) { _logger.LogError($"Error Within Default Search Algorithm - Exception: {e.Message}"); }
            }
            int pageSize = 15;
            ViewData["TotalPages"] = (Rentals.Count() / 15) - (Rentals.Count() % 15);
            //var RentalVM = from d in Rentals select new RentalViewModel4 {
            //                ID = d.ID,
            //                DailyRental = d.DailyRental,
            //                DateCreated = d.DateCreated,
            //                DueDate = d.DueDate,
            //                FirstName = d.FirstName,
            //                LastName = d.LastName,
            //                Address = d.Address,
            //                City = d.City,
            //                State = d.State,
            //                EmailAddress = d.EmailAddress,
            //                PhoneNumber = d.PhoneNumber,
            //                PhoneNumber2 = d.PhoneNumber2,
            //                PartialReturn = d.PartialReturn,
            //                Returned = d.Returned
            //};

            //var RentalVMQuery = RentalVM.AsQueryable();
            try
            {
                return View(await PaginatedList<Rental>.CreateAsync(Rentals.AsNoTracking(),page ?? 1, pageSize));
            }
            catch (Exception e)
            {
                _logger.LogError($"Error creating paginated list in Index Method - Exception: {e.Message}");
                var blankList = new PaginatedList<Rental>(new List<Rental>(),0,0,15);
                return View(blankList);
            }
            //return View(await PaginatedList<RentalViewModel4>.CreateAsync(RentalVM, page ?? 1, pageSize));
        }

        List<int> idset = new List<int>();

        [Authorize]
        [HttpGet]

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RL</title>

    <environment names="Development,Backup">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css"/>
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/normalize.css"/>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        @*<link href="~/lib/jquery-ui-custom/jquery-ui.min.css" rel="stylesheet" />*@
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:black;" id="navBar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                <span style="font-family:FontAwesome;margin-right:3px;">&#xf015;</span>Home
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                    <li>
                        <a asp-area="" asp-controller="Rentals" asp-action="Index" title="View Rentals">
                        <span style="font-family:FontAwesome;margin-right:5px;">&#xf03a;</span>Rentals
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Manage" asp-action="Reports" title="Report Builder">
                            <span style="font-family:FontAwesome;margin-right:5px;">&#xf016;</span>Reports
                        </a>
                    </li>
                    }
                </ul>
                    @if (Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "Backup")
                    {
                        <p id="backup-environment-header">OFFLINE MODE</p>
                    }
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <div class="printHide">
            <hr />
            <footer>
                <p>&copy; 2017 - Seattle Ski</p>
            </footer>
        </div>
    </div>

    <environment names="Development,Backup">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
    </environment>
        <script src="~/js/jquery.suggest.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/validation.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
</body>
</html>